export const entriesTableColumns = [
  {
    title: '',
    dataIndex: 'id_sds',
    data_type: 'string',
    is_sort: true,
    number_in_row: 2,
  },
  {
    title: 'Полное наименование компании',
    dataIndex: 'full_name',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Сокращенное название компании',
    dataIndex: 'short_name',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Регистрационный номер',
    dataIndex: 'reg_no',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Дата регистрации',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Рег.компании',
    dataIndex: 'reg_comp',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Сайт компании',
    dataIndex: 'site',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Адрес',
    dataIndex: 'area',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Статус',
    dataIndex: 'status',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
];
