export const entriesTableColumns = [
  {
    title: '',
    dataIndex: 'id_sds',
    data_type: 'string',
    is_sort: true,
    number_in_row: 2,
  },
  {
    title: 'Статус ',
    dataIndex: 'status',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Наименование СДС',
    dataIndex: 'full_name',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Регистрационный номер СДС',
    dataIndex: 'reg_no',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Держатель',
    dataIndex: 'reg_comp',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Дата регистрации',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
];

export const entriesTableColumns2 = [
  {
    title: '',
    dataIndex: 'id_sds',
    data_type: 'string',
    is_sort: true,
    number_in_row: 2,
  },
  {
    title: 'Наименование',
    dataIndex: 'status',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'ИНН',
    dataIndex: 'full_name',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'СДС',
    dataIndex: 'reg_no',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Область сертификации',
    dataIndex: 'reg_comp',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Количество аттестованных экспертов',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Дата решения об аккредитации',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
];

export const entriesTableColumns3 = [
  {
    title: '',
    dataIndex: 'id_sds',
    data_type: 'string',
    is_sort: true,
    number_in_row: 2,
  },
  {
    title: '№ сертификата (аттестата)',
    dataIndex: 'status',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Фамилия, имя, отчество эксперта',
    dataIndex: 'full_name',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Дата выдачи аттестата',
    dataIndex: 'reg_no',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Срок действия сертификата (аттестата)',
    dataIndex: 'reg_comp',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Количество аттестованных экспертов',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Область деятельности (аттестации) эксперта	',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
];


export const entriesTableColumns4 = [
  {
    title: '',
    dataIndex: 'id_sds',
    data_type: 'string',
    is_sort: true,
    number_in_row: 2,
  },
  {
    title: '№ сертификата',
    dataIndex: 'status',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Наименование организации',
    dataIndex: 'full_name',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'ИНН',
    dataIndex: 'reg_no',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Срок действия сертификата',
    dataIndex: 'reg_comp',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Наименование',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'ОС',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Индекс',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'Статус сертификата',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  },
  {
    title: 'ОКВЭД',
    dataIndex: 'reg_date',
    data_type: 'string',
    is_sort: true,
    number_in_row: 1,
  }
];
